In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
driver=pd.read_csv('train.csv')
driver

id  target  ps_ind_01  ps_ind_02_cat  ps_ind_03  ps_ind_04_cat  \
0             7       0          2              2          5              1   
1             9       0          1              1          7              0   
2            13       0          5              4          9              1   
3            16       0          0              1          2              0   
4            17       0          0              2          0              1   
5            19       0          5              1          4              0   
6            20       0          2              1          3              1   
7            22       0          5              1          4              0   
8            26       0          5              1          3              1   
9            28       1          1              1          2              0   
10           34       0          5              2          2              0   
11           35       0          2              1          3              1   
12           36       0          2              1          1              1   
13           43       0          1              1          3              1   
14           46       0          5              1         11              0   
15           48       0          5              1          3              1   
16           50       0          1              2          1              0   
17           58       0          5              1          6              0   
18           61       0          5              1          8              0   
19           64       1          0              1          2              1   
20           65       0          0              1          2              0   
21           66       0          0              1          5              1   
22           72       0          5              3          6              1   
23           74       0          2              1          2              1   
24           77       0          0              1          2              0   
25           78       0          0              1          7              0   
26           79       0          0              1          4              1   
27           80       0          4              1          6              0   
28           84       1          0              2          0              1   
29           85       0          3              2          2              0   
...         ...     ...        ...            ...        ...            ...   
595182  1487945       0          0              1          2              0   
595183  1487951       0          1              1          9              0   
595184  1487952       0          1              1          5              0   
595185  1487954       0          0              2          8              1   
595186  1487957       0          0              1          3              1   
595187  1487958       0          0              1          7              0   
595188  1487962       0          2              1          3              0   
595189  1487963       0          3              1          9              0   
595190  1487964       0          1              2          3              0   
595191  1487968       0          5              1          3              0   
595192  1487973       0          0              1          1              0   
595193  1487975       0          0              2          0              0   
595194  1487976       0          0              1          7              1   
595195  1487980       0          0              3          3              1   
595196  1487983       0          1              1          2              0   
595197  1487988       0          1              1          7              1   
595198  1487990       0          5              1          7              1   
595199  1487992       0          3              1          3              1   
595200  1487994       0          1              1          1   

In [2]:
driver.isnull().sum()

id                0
target            0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0


In [3]:
driver.drop(columns='id',inplace=True)

In [4]:
driver.dtypes

target              int64
ps_ind_01           int64
ps_ind_02_cat       int64
ps_ind_03           int64
ps_ind_04_cat       int64
ps_ind_05_cat       int64
ps_ind_06_bin       int64
ps_ind_07_bin       int64
ps_ind_08_bin       int64
ps_ind_09_bin       int64
ps_ind_10_bin       int64
ps_ind_11_bin       int64
ps_ind_12_bin       int64
ps_ind_13_bin       int64
ps_ind_14           int64
ps_ind_15           int64
ps_ind_16_bin       int64
ps_ind_17_bin       int64
ps_ind_18_bin       int64
ps_reg_01         float64
ps_reg_02         float64
ps_reg_03         float64
ps_car_01_cat       int64
ps_car_02_cat       int64
ps_car_03_cat       int64
ps_car_04_cat       int64
ps_car_05_cat       int64
ps_car_06_cat       int64
ps_car_07_cat       int64
ps_car_08_cat       int64
ps_car_09_cat       int64
ps_car_10_cat       int64
ps_car_11_cat       int64
ps_car_11           int64
ps_car_12         float64
ps_car_13         float64
ps_car_14         float64
ps_car_15         float64
ps_calc_01  

In [5]:
y = driver['target']
driver.drop(columns='target',inplace=True)

from sklearn.model_selection import train_test_split 


X_train,X_test,y_train,y_test = train_test_split( driver,y,test_size=0.2,random_state=24)


In [6]:

from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=2)
X_train_res,y_train_res = sm.fit_sample(X_train,y_train.ravel())

print('After OverSampling,the shape of train_X:{}'.format(X_train_res.shape))
print('After OverSampling ,the shape of train_y:{}\n'.format(y_train_res.shape))

print("After OverSampling,count of label '1':{}".format(sum(y_train_res==1)))
print("After OverSampling,count of label '0':{}".format(sum(y_train_res==0)))

After OverSampling,the shape of train_X:(917614, 57)
After OverSampling ,the shape of train_y:(917614,)

After OverSampling,count of label '1':458807
After OverSampling,count of label '0':458807


In [7]:
y_train_res

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=60,random_state=48)
rf.fit(X_train_res,y_train_res)
prediction=rf.predict(X_test)
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
from sklearn.linear_model import LogisticRegression
LogR= LogisticRegression()
LogR.fit(X_train_res,y_train_res)
predicted=LogR.predict(X_test)
predicted

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([1, 0, 0, ..., 1, 1, 0], dtype=int64)

In [10]:
from sklearn.metrics import f1_score
f1_score(y_test,predicted)

0.09452965824779917

In [11]:
from sklearn.metrics import confusion_matrix, precision_score,accuracy_score

In [12]:
confusion_matrix(y_test,predicted)

array([[69476, 45235],
       [ 1873,  2459]], dtype=int64)

In [13]:
precision_score(y_test,predicted)

0.0515578479473309

In [14]:
accuracy_score(y_test,predicted)

0.6042774459649034

In [ ]:
from sklearn.model_selection import GridSearchCV
dictionary = {'n_estimators':np.arange(75,80,85),
              'max_depth':[2,4,6,7],
              'min_samples_split':[2,5,7,6],
              'min_samples_leaf':[2,4,5,6,7]
             
             }
grid = GridSearchCV(estimator=rf,param_grid=dictionary,cv=5)
grid.fit(X_train_res,y_train_res)
grid.best_params_
#grid.best_score_

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(n_estimators=75,max_depth = 7,min_samples_leaf = 2,min_samples_split = 2,random_state=48)
rf1.fit(X_train_res,y_train_res)
pred1=rf.predict(X_test)
pred1

In [ ]:
from sklearn.metrics import confusion_matrix,f1_score,balanced_accuracy_score,accuracy_score,roc_auc_score,roc_curve,precision_score,precision_recall_curve,roc_auc_score
import matplotlib.pyplot as plt
confusion_matrix(y_test,pred1)

y_pred_proba=rf1.predict_proba(X_test)[::,1]

y_pred_proba

fpr,tpr,thresholds=roc_curve(y_test,y_pred_proba)



plt.plot(fpr,tpr)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')



In [ ]:
precision_score(y_test,pred1)

In [ ]:
f1_score(y_test,pred1)

In [ ]:
balanced_accuracy_score(y_test,pred1)

In [ ]:
accuracy_score(y_test,pred1)